# Copyright 2018 The CRC32C Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file. See the AUTHORS file for names of contributors.

licenses(["notice"])  # BSD

package(default_visibility = ["//:__subpackages__"])
