# DO NOT EDIT -- GENERATED BY CMake -- Change the CMakeLists.txt file if needed
crc32c_test_sources = [
    ".build/include/crc32c/crc32c_config.h",
    "src/crc32c_arm64_unittest.cc",
    "src/crc32c_extend_unittests.h",
    "src/crc32c_portable_unittest.cc",
    "src/crc32c_prefetch_unittest.cc",
    "src/crc32c_read_le_unittest.cc",
    "src/crc32c_round_up_unittest.cc",
    "src/crc32c_sse42_unittest.cc",
    "src/crc32c_unittest.cc",
    "src/crc32c_test_main.cc",
]
