# DO NOT EDIT -- GENERATED BY CMake -- Change the CMakeLists.txt file if needed
crc32c_HDRS = [
    "src/crc32c_arm64.h",
    "src/crc32c_arm64_linux_check.h",
    "src/crc32c_internal.h",
    "src/crc32c_prefetch.h",
    "src/crc32c_read_le.h",
    "src/crc32c_round_up.h",
    "src/crc32c_sse42.h",
    "src/crc32c_sse42_check.h",
    "include/crc32c/crc32c.h",
]

crc32c_SRCS = [
    "src/crc32c_portable.cc",
    "src/crc32c.cc",
]
